name: GitHub Classroom Workflow

on:
  push:
    branches:
    - '*'
    - '!badges'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # add id to action so outputs can be used
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: clean up
        run: make clean

      # make dir for badges
      - name: create or switch to badges branch
        run: |
          if ! git switch badges > /dev/null 2>&1
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout --orphan badges
            git rm --cached $(git ls-files)
            echo '# Badges branch' > README.md
            mkdir -p .github/badges
            touch .github/badges/.gitkeep
            git add README.md
            git add .github/badges/.gitkeep
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m 'Add dedicated README and directory'
          fi

      - name: Make points badge
        uses: emibcn/badge-action@v1.2.4
        with:
          LABEL: 'Points'
          STATUS: ${{ steps.autograder.outputs.points }}
          COLOR: cyan
          path: '.github/badges/points.svg'

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: badge
          path: '.github/badges/points.svg'
          if-no-files-found: error

      # commit and push badge if score has changed
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git diff-index --quiet HEAD || git commit -m "Add/Update badge"
        continue-on-error: true

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
          force: true

      - name: Check on failures
        if: steps.autograder.outcome == 'failure'
        run: echo "Not all tests in autograding passed" && exit 1
